In [1]:
import numpy as numpy
import pandas as pd
import difflib
import warnings
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
warnings.filterwarnings('ignore')

In [ ]:
PATH = "./data.csv"
data = pd.read_csv(PATH)
data.head()

,isbn13,isbn10,title,subtitle,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count
0,9780002005883,0002005883,Gilead,NaN,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0
1,9780002261982,0002261987,Spider's Web,A Novel,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0
2,9780006163831,0006163831,The One Tree,NaN,Stephen R. Donaldson,American fiction,http://books.google.com/books/content?id=OmQaw...,Volume Two of Stephen Donaldson's acclaimed se...,1982.0,3.97,479.0,172.0
3,9780006178736,0006178731,Rage of angels,NaN,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0
4,9780006280897,0006280897,The Four Loves,NaN,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   int64
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6711 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 638.6+ KB

In [4]:
data['isbn13'] = str(data['isbn13'])
data['categories'] = data['categories'].fillna('None')

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6810 entries, 0 to 6809
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   isbn13          6810 non-null   object
 1   isbn10          6810 non-null   object
 2   title           6810 non-null   object
 3   subtitle        2381 non-null   object
 4   authors         6738 non-null   object
 5   categories      6810 non-null   object
 6   thumbnail       6481 non-null   object
 7   description     6548 non-null   object
 8   published_year  6804 non-null   float64
 9   average_rating  6767 non-null   float64
 10  num_pages       6767 non-null   float64
 11  ratings_count   6767 non-null   float64
dtypes: float64(4), object(8)
memory usage: 638.6+ KB

In [6]:
relevant_titles = ['title', 'authors', 'categories', 'average_rating', 'num_pages', 'ratings_count']
relevant_titles_str = [x for x in relevant_titles if data[x].dtype == 'object']
relevant_titles_num = [x for x in relevant_titles if not x in relevant_titles_str]
selected_features = data[relevant_titles]

In [7]:
relevant_titles_num

['average_rating', 'num_pages', 'ratings_count']

In [8]:
data.describe()

       published_year  average_rating    num_pages  ratings_count
count     6804.000000     6767.000000  6767.000000   6.767000e+03
mean      1998.630364        3.933284   348.181026   2.106910e+04
std         10.484257        0.331352   242.376783   1.376207e+05
min       1853.000000        0.000000     0.000000   0.000000e+00
25%       1996.000000        3.770000   208.000000   1.590000e+02
50%       2002.000000        3.960000   304.000000   1.018000e+03
75%       2005.000000        4.130000   420.000000   5.992500e+03
max       2019.000000        5.000000  3342.000000   5.629932e+06

#### Genres

### Data Processing

In [9]:
for feature in relevant_titles_str:
    selected_features[feature] = selected_features[feature].fillna('')
for feature in relevant_titles_num:
    selected_features[feature] = selected_features[feature].fillna(0)

In [10]:
combined_features = selected_features['authors'] + ' ' + selected_features['title'] + ' ' + selected_features['categories']

In [11]:
selected_features.isna().sum()

title             0
authors           0
categories        0
average_rating    0
num_pages         0
ratings_count     0
dtype: int64

In [12]:
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(combined_features)

In [13]:
similarity = cosine_similarity(feature_vectors, feature_vectors)

In [14]:
list_of_all_titles = selected_features['title'].to_list()
list_of_all_genres = data['categories'].to_list()

In [15]:
book_name = input('Enter your favourite Book name: ')
type(book_name)

Enter your favourite Book name:  Wuthering heights

str

In [16]:
find_close_match = difflib.get_close_matches(book_name, list_of_all_titles)
print(find_close_match)

['Wuthering Heights', 'Wuthering Heights', 'Wuthering Heights']

In [17]:
close_match = find_close_match[0]
index_of_the_book = selected_features[selected_features.title == close_match].index[0]

In [18]:
similarity_score = list(enumerate(similarity[index_of_the_book]))

In [19]:
sorted_similar_books = sorted(similarity_score, key = lambda x: x[1], reverse=True)
print(sorted_similar_books)

[(856, 1.0000000000000002), (2453, 0.8703852349478035), (3064, 0.8703852349478035), (1005, 0.27690004878500996), (3420, 0.2627922490745036), (1519, 0.23050961593846234), (2731, 0.22550646139083383), (6260, 0.22536573334070406), (1370, 0.22490435850808355), (1516, 0.22117837022220282), (1517, 0.22117837022220282), (1525, 0.21877667288328487), (5664, 0.20337778271566448), (2175, 0.2010088514254994), (495, 0.1846267592758187), (4595, 0.16992841393705044), (3903, 0.14352788950737885), (5297, 0.14182150382134168), (5766, 0.03306452696545746), (1196, 0.026192571560851075), (3005, 0.02322211305670495), (2328, 0.02259313496664116), (1456, 0.022499309707019435), (1422, 0.02013337200210638), (350, 0.019906186594019354), (6645, 0.019764306065724345), (691, 0.019719326053879525), (3417, 0.019487057916950247), (2979, 0.019174602165272007), (2059, 0.018832791068868163), (5832, 0.018803913588886716), (3253, 0.0185152634500158), (4104, 0.018402937537964237), (3837, 0.01812126450772219), (1130, 0.018113100885402435), (3277, 0.01770841625391622), (6751, 0.017451891571489554), (3049, 0.017427844083311054), (2973, 0.017357595675973097), (6077, 0.01735268310593872), (2435, 0.01721740501268629), (5229, 0.017205083467778413), (5653, 0.017195181398848024), (5438, 0.01718389046172098), (1599, 0.01712614833086448), (3495, 0.01703886154111249), (3575, 0.016991808362931644), (2987, 0.016883019995417095), (3239, 0.016850991712874082), (1595, 0.01679167339842596), (6073, 0.01675102365658674), (894, 0.01672275585265717), (947, 0.01668392565812705), (5786, 0.01665688951020974), (1062, 0.016612943544419046), (3265, 0.016612943544419046), (4410, 0.016595961736965543), (5557, 0.016595961736965543), (1627, 0.01656566228938611), (3009, 0.0165281118680788), (3817, 0.01652049414461503), (3835, 0.016520001835420055), (5897, 0.016520001835420055), (2951, 0.016504084330359554), (914, 0.016482534361272085), (5591, 0.01647327044052948), (4016, 0.016441289263431812), (5237, 0.01637437284802008), (1528, 0.0163348410440225), (1598, 0.0163348410440225), (4939, 0.016296006507176733), (3196, 0.016271918788475715), (445, 0.016253783967886893), (5906, 0.016221394569710668), (4405, 0.016213784099027635), (1349, 0.0161861881332654), (3731, 0.0161861881332654), (304, 0.016166073583680943), (2954, 0.016105527447858935), (2974, 0.016084420440794944), (1736, 0.016082294697230607), (1219, 0.016038482652823184), (5165, 0.0160064383439451), (4458, 0.015989257688704867), (2290, 0.015944408663652442), (968, 0.01593618798281808), (3168, 0.01593618798281808), (6410, 0.01587332160957303), (3259, 0.015866361850868583), (3272, 0.015855262293778406), (2581, 0.015851647989463983), (2857, 0.01585131205215278), (3095, 0.015840689894494813), (1921, 0.0158150875772908), (1199, 0.015742908267356328), (3639, 0.01573920514373515), (885, 0.015727443264136644), (433, 0.015726328539623847), (4860, 0.015704721838515238), (521, 0.01559896209309149), (1632, 0.01553322188357294), (2773, 0.015478408107933305), (2712, 0.015434448534797633), (685, 0.015398094266792818), (2191, 0.01536207762815784), (1417, 0.015355542913304392), (782, 0.015329381231407936), (186, 0.015322189398970964), (2225, 0.015322189398970964), (2652, 0.015311194300620085), (3447, 0.015255550293061524), (123, 0.01525254610852555), (732, 0.015245179089989961), (750, 0.015245179089989961), (4432, 0.015239500232002138), (2613, 0.015222994752617975), (2337, 0.015214006051598885), (2211, 0.015206154723552672), (3626, 0.015191199771797642), (3014, 0.015187447424389749), (4677, 0.015174122464852474), (1414, 0.01517223872822734), (439, 0.0151550069645621), (1415, 0.01514733965265062), (5701, 0.01514733965265062), (4835, 0.01514247866187834), (3503, 0.015130283308872079), (183, 0.015130266423139718), (6205, 0.015125235959721988), (2285, 0.015118407474942789), (2287, 0.015118407474942789), (2288, 0.015118407474942789), (2291, 0.015118407474942789), (2817, 0.015118381671808902), (2326, 0.015111398821766682), (4117, 0.015085854011495195), (4712, 0.015079033215407451), (1744, 0.015075955049761513), (5983, 0.015069727167044564), (4839, 0.015068009157366854), (4983, 0.015057090870917961), (3159, 0.015045622369073747), (3880, 0.015038824353128288), (4747, 0.015036883572534224), (1174, 0.014999222852896031), (2475, 0.01499430537326305), (4026, 0.014993984975819169), (4802, 0.014993984975819169), (2181, 0.014970580372869642), (6226, 0.01496832295850531), (3863, 0.014946904196028407), (141, 0.014946754897305835), (2242, 0.014930815627103484), (2980, 0.014930815627103484), (1006, 0.014930658667207072), (1032, 0.014930658667207072), (214, 0.014923719977384472), (1831, 0.014921976577976687), (1832, 0.014921976577976687), (5696, 0.0149165838474543), (2664, 0.014913829075258617), (2877, 0.014903590907365757), (2879, 0.014903590907365757), (5901, 0.014903590907365757), (4775, 0.014900851431031703), (4781, 0.014900851431031703), (5350, 0.014888577738674469), (5789, 0.014880134546614307), (247, 0.014854860715744773), (171, 0.014843360841871081), (1818, 0.014839456524813789), (2970, 0.014811876396794564), (5196, 0.014808675740660348), (174, 0.014790874301350116), (4729, 0.014776115915072125), (422, 0.014774719538821642), (4050, 0.014768295842640927), (4737, 0.014752262518063755), (2695, 0.014750249698187697), (1118, 0.014744268874533851), (1158, 0.014744268874533851), (5890, 0.01474318951019264), (1645, 0.014738209816977202), (3254, 0.014720738487090589), (4898, 0.014713674597406749), (3233, 0.01471216936684544), (4897, 0.014711858752276957), (2754, 0.014696608181119892), (2950, 0.014696608181119892), (5848, 0.014696608181119892), (1977, 0.014694764625606326), (2625, 0.014694480612056953), (1552, 0.014686556601732622), (3968, 0.01465671471881859), (415, 0.014654547643804807), (1485, 0.014650274175698), (2846, 0.01464413394103823), (5176, 0.01464413394103823), (2998, 0.014637513080581694), (3544, 0.01463671437992475), (3564, 0.014631259154079241), (2598, 0.01462805035763308), (3688, 0.01462426043861472), (4006, 0.014624044652238556), (6236, 0.014619809266634311), (2828, 0.014617415758786757), (2117, 0.014613833930059793), (3728, 0.014613833930059793), (4017, 0.014613833930059793), (3256, 0.014612089969580685), (2485, 0.014603985439727093), (3551, 0.014592221422506468), (4906, 0.014582001670989695), (6750, 0.014578944517326909), (6754, 0.014578944517326909), (3202, 0.014575046457052227), (3745, 0.014572213247091848), (3876, 0.014565688725293362), (1976, 0.014560921704706933), (3247, 0.014560921704706933), (3827, 0.014559443739297665), (3535, 0.014548915018750583), (3608, 0.014548659121674277), (5048, 0.014540502409707548), (1146, 0.014534714585391476), (1748, 0.01452773567055486), (1857, 0.014519581262512472), (1614, 0.014518347135115512), (2249, 0.014499490916114566), (4248, 0.014499017900079741), (1637, 0.014497925106097079), (146, 0.014497793841630986), (3630, 0.014497793841630986), (776, 0.014496826163103115), (5384, 0.014494289550636254), (5191, 0.014483949486107872), (6411, 0.014483949486107872), (4143, 0.01448251623005636), (4799, 0.014476853889216957), (4676, 0.014474722880033888), (6452, 0.014474722880033888), (5960, 0.014468112683564209), (130, 0.014463447062404522), (351, 0.014463447062404522), (4606, 0.014458757505133596), (5517, 0.014458757505133596), (1613, 0.014446981302534264), (2622, 0.014444318901648425), (5377, 0.014443605081417822), (435, 0.014440443264650679), (3529, 0.014436662230685984), (3864, 0.014431088083283666), (4425, 0.014428268036528679), (5562, 0.014416690795604033), (1482, 0.014413953359741853), (722, 0.014403461322647635), (3973, 0.014403142005205217), (866, 0.014399728920016274), (3980, 0.01439791447771876), (3359, 0.014393389013125783), (1584, 0.01439129832748994), (2313, 0.014380749959589104), (887, 0.014373271018056214), (2884, 0.014371309857959116), (5723, 0.014348127664981267), (4746, 0.014338143253008228), (5772, 0.014338130623667135), (2514, 0.014330490603143379), (3814, 0.01432916272434119), (4731, 0.014310375367456062), (353, 0.014304046976388507), (2653, 0.014303489296524113), (2279, 0.014298104535924753), (2785, 0.014298104535924753), (2111, 0.014293295903638866), (414, 0.014290282525201222), (5385, 0.014289842992925534), (1892, 0.014284494630913115), (1578, 0.01427866666416916), (2847, 0.01427866666416916), (2523, 0.01427772117670613), (3016, 0.0142770105693626), (163, 0.014276188538422713), (1590, 0.01426213172007525), (2867, 0.01426213172007525), (655, 0.014259747091942242), (678, 0.014259747091942242), (4340, 0.014259747091942242), (2632, 0.0142561443300826), (2821, 0.014253986167162282), (3978, 0.014244660052200257), (3963, 0.014243796879511635), (3509, 0.014235648367757724), (2592, 0.014233337172675768), (6521, 0.014228965580645486), (3354, 0.014228579687553014), (909, 0.014227197566163892), (2340, 0.014212916835373807), (3019, 0.01420206106625329), (2019, 0.014196779672635754), (4842, 0.014173350122076434), (2071, 0.014171931810609708), (4229, 0.014171918944958357), (5780, 0.014169528751172623), (3006, 0.014168769805552072), (3505, 0.014162016262437743), (6434, 0.014155280326789373), (374, 0.014154653319900895), (3195, 0.014152250696004244), (6313, 0.014149772808516333), (6642, 0.014149772808516333), (566, 0.01414371155280877), (2648, 0.014139425874767669), (2266, 0.01413893303669692), (5022, 0.014138094754227162), (1568, 0.014137541220170465), (675, 0.01413273573713603), (1948, 0.014130902223453205), (1836, 0.014128031544942072), (3108, 0.01412421422773808), (402, 0.01412200382915543), (341, 0.014118699718654737), (2618, 0.014118609298743543), (1974, 0.01411198736967993), (443, 0.014111611177007734), (1618, 0.01410847694891792), (2229, 0.01410847694891792), (2516, 0.014099598859347286), (2338, 0.014098120107693245), (3882, 0.014093031953702198), (2977, 0.014088593220395504), (2910, 0.014087368823394569), (60, 0.014083294588212277), (180, 0.014081758247666762), (931, 0.014081513990348255), (932, 0.014081513990348255), (2335, 0.01407886818141528), (3047, 0.014077925294309209), (3067, 0.014075189107647245), (5370, 0.014075116323952898), (5697, 0.014075047357546833), (4805, 0.01406740782547903), (5508, 0.014066452399754488), (4611, 0.014056663524868762), (1472, 0.014055348818945917), (2752, 0.014053181359285648), (951, 0.014051530551488617), (442, 0.01405068774394907), (5303, 0.014038645729490984), (2681, 0.014034197224932763), (1798, 0.014027395118833833), (6290, 0.014026114713007692), (1887, 0.014011721807188729), (1078, 0.014009798788823304), (5171, 0.014007651614628717), (540, 0.014005526318283078), (2265, 0.014005526318283078), (2270, 0.014005526318283078), (2272, 0.014005526318283078), (151, 0.013997759464404345), (1476, 0.013996002781869908), (1657, 0.013990654035944074), (1522, 0.013984072422832242), (3515, 0.013983947632314066), (4804, 0.013979101345203785), (4344, 0.013978391218703123), (1512, 0.01396300686554433), (609, 0.013959712921287419), (2831, 0.01395958197969432), (5367, 0.013946960388124218), (4382, 0.013944398559789727), (925, 0.013940708337510392), (956, 0.013940653630857629), (2147, 0.013940653630857629), (4140, 0.013937582005234572), (2860, 0.01393646558987967), (2917, 0.01393074074427173), (1918, 0.013929199394504092), (5509, 0.013926263215544845), (2608, 0.013921769360914051), (1057, 0.013915823293940971), (3028, 0.013903804639718112), (5383, 0.013903595970207206), (2602, 0.013902384235131657), (2694, 0.013895234522040611), (2733, 0.013895234522040611), (2946, 0.013894183891867388), (1035, 0.013892896298062686), (4923, 0.013880208019269851), (5272, 0.013879171429674415), (4439, 0.013875916337412754), (5364, 0.013875916337412754), (3013, 0.013875716806985882), (2447, 0.013866994009798881), (4443, 0.013866994009798881), (2741, 0.013866850012621838), (6282, 0.013866807316382759), (5043, 0.013866182276560151), (2283, 0.013859439948769984), (2944, 0.013857242503359358), (3806, 0.013856370891020854), (6458, 0.013851184401947863), (2025, 0.013847724833564895), (3856, 0.01384690470935014), (963, 0.013839173781986649), (3708, 0.013839173781986649), (5520, 0.01383885303827264), (5233, 0.013837628742776706), (1166, 0.013834784609869777), (3238, 0.013834591906062083), (72, 0.013832783355225134), (5382, 0.013828986783079925), (468, 0.013824748087418546), (1619, 0.013821569328115102), (319, 0.013820772968300128), (1194, 0.013812309032900923), (2141, 0.013812309032900923), (1611, 0.01380705951846293), (2923, 0.013806700856011852), (386, 0.013802975409106336), (6419, 0.01379849036795785), (3862, 0.013794711415058485), (4757, 0.013785110243995598), (4139, 0.013780492178059413), (4877, 0.013780005002579991), (3624, 0.013774648601158651), (1881, 0.013771156806788103), (2654, 0.013768760105467173), (3802, 0.013765331720132558), (432, 0.01376306920102082), (6111, 0.01375587956156751), (5123, 0.013755013230535865), (3102, 0.01375122167790876), (3103, 0.01375122167790876), (5629, 0.013750375721129573), (4614, 0.013742959388295685), (4615, 0.013742959388295685), (936, 0.013738094986844201), (1108, 0.013735570715385977), (2832, 0.013734567185766705), (2550, 0.013732384753542099), (5390, 0.0137283306602147), (3751, 0.013726175075991295), (5042, 0.013725602212208398), (5378, 0.013722836353655333), (2997, 0.013719081146003155), (2301, 0.013717355976749512), (3508, 0.013714486092773268), (541, 0.013713204527614802), (974, 0.013705389203121929), (2003, 0.013693928494791657), (2010, 0.013693928494791657), (2051, 0.013690931161575786), (2861, 0.013688689374825319), (4462, 0.013679407674948275), (676, 0.01367813874640968), (1880, 0.01367813874640968), (860, 0.013675535971020244), (3853, 0.013673318000430156), (2289, 0.013671504940364176), (5020, 0.013669795222233013), (3896, 0.013664355453894248), (538, 0.01365923573741934), (4549, 0.013655114989008359), (3488, 0.013651745856568153), (738, 0.0136507787218102), (2526, 0.0136507787218102), (5163, 0.0136507787218102), (1820, 0.013647936358266798), (3364, 0.013647745052595113), (1625, 0.01364437034196823), (1926, 0.013641634347529033), (5232, 0.013641123163509386), (4319, 0.01363862360037237), (5507, 0.013637517734072986), (5657, 0.013633245461053684), (2684, 0.01363302275508862), (2732, 0.01363302275508862), (3249, 0.013632758626150996), (2837, 0.013628148231259334), (677, 0.013627716114751042), (1782, 0.01362007274022281), (5756, 0.013618511383476166), (4145, 0.013618105721336222), (1111, 0.013615111149018035), (6061, 0.013614543310085261), (113, 0.013613509643827454), (2996, 0.013605617632581533), (937, 0.013605581155147024), (2969, 0.013605342634364626), (3836, 0.013605342634364626), (1620, 0.013604180955303892), (1617, 0.013603323202337508), (5172, 0.013600147987666629), (3353, 0.013600085096865241), (3542, 0.01360003450469992), (2564, 0.013598946728105845), (5379, 0.01359864527766226), (3023, 0.013598585905646105), (1809, 0.013594882014174255), (757, 0.013594631297296565), (3355, 0.013594478006874399), (2126, 0.013584444829675484), (780, 0.013582177203995923), (2890, 0.013581555444696086), (3538, 0.013578849932040653), (2981, 0.013578456992140553), (924, 0.013572349991170095), (344, 0.013570288779678794), (6314, 0.0135661824516557), (1606, 0.01356499997271835), (4106, 0.013564565332657487), (2107, 0.013563032977857393), (2573, 0.013558844806627529), (1464, 0.013554402034782437), (2351, 0.01355435529930917), (5975, 0.013553228298106632), (6342, 0.013553228298106632), (5680, 0.013551727201940596), (3556, 0.013550105807505562), (985, 0.013545121992881734), (708, 0.013540667130249517), (4843, 0.013540667130249517), (1994, 0.013537353448912395), (1810, 0.013534105524490024), (3472, 0.013533369701516293), (1483, 0.01352938453296998), (5898, 0.013528988930948144), (1772, 0.013528570067392344), (5529, 0.013526944018943056), (153, 0.013525906195270696), (209, 0.013525906195270696), (283, 0.013525906195270696), (3530, 0.013520599108178094), (852, 0.01351864132345845), (2350, 0.013512878393290038), (2401, 0.013512374895762238), (3875, 0.013512006220625388), (850, 0.013509768674316094), (6395, 0.013508181034196423), (4714, 0.013507328521225364), (5144, 0.013506903907333634), (5973, 0.013505427588869134), (4377, 0.013503777547599983), (4800, 0.013501787086690416), (2580, 0.01349827649442765), (3558, 0.01349827649442765), (892, 0.013497388549567791), (1072, 0.013497388549567791), (1151, 0.013497388549567791), (3043, 0.013481174732503907), (1439, 0.01347468343835425), (690, 0.013473888164751025), (5198, 0.013473102606235304), (401, 0.013469926245173354), (4964, 0.013468707696694334), (2840, 0.013460358042893021), (3271, 0.01345931346721097), (215, 0.013457012422166936), (3194, 0.013453159404328539), (1920, 0.013451155611279322), (6566, 0.013448524896711571), (2635, 0.013445837616841242), (1771, 0.013444917283367623), (6755, 0.013443388816440404), (6756, 0.013443388816440404), (1639, 0.013439408395432305), (4899, 0.01343757942440611), (3869, 0.013437222502777018), (2978, 0.013435828260243029), (4027, 0.01343204743614462), (2742, 0.013431451934752467), (4074, 0.01342965267855955), (4758, 0.01342900835484046), (1932, 0.013428678075626073), (2700, 0.013424462341551617), (1897, 0.013423246868275101), (3021, 0.013423246868275101), (5891, 0.013422804747225573), (4745, 0.01341780526767721), (126, 0.013414429371313357), (923, 0.013411984456836156), (4589, 0.013411984456836156), (4718, 0.013406140405183897), (1481, 0.013402763835166585), (234, 0.01339938222268608), (3878, 0.013397154088325104), (149, 0.013396553845367407), (6043, 0.013395505476771001), (5141, 0.013392737224493453), (891, 0.013392256314998234), (4610, 0.013390631215969255), (4905, 0.013386141399075277), (3726, 0.013383998447081989), (1813, 0.013380458174485705), (1899, 0.01338001727361392), (4185, 0.01337997873282725), (4186, 0.01337997873282725), (3050, 0.013373529231307205), (1570, 0.013373104986022125), (4613, 0.013372886886836542), (3543, 0.013372519120793163), (3566, 0.013372519120793163), (4192, 0.013370549651764561), (187, 0.013370429575632335), (3572, 0.013367900314989483), (684, 0.013364804547923654), (4763, 0.01335704056514748), (1605, 0.013350472902611245), (2833, 0.013350446181939373), (2966, 0.013350088907384098), (5003, 0.013349231934932326), (4346, 0.013347268734181685), (729, 0.013337344978418082), (2597, 0.013332684332369268), (3536, 0.013332684332369268), (1181, 0.013332260054627013), (2158, 0.01333106332066583), (4947, 0.01333053494126924), (3539, 0.013329990122435093), (4179, 0.013327529753212535), (2991, 0.013326668072231861), (4053, 0.013323240386405899), (5372, 0.013322648866142246), (3870, 0.013320627592881452), (5915, 0.01332039216316913), (2011, 0.013319145256587074), (1718, 0.013315406651228457), (653, 0.01331257708326664), (2506, 0.013308562175450392), (2767, 0.013308562175450392), (2711, 0.013308209238890525), (1900, 0.013305802264345344), (200, 0.013305279379653704), (6522, 0.013304747540089333), (1871, 0.01330329904216712), (769, 0.013300975691084325), (1986, 0.01329527087005085), (3897, 0.01329420855568983), (5335, 0.013292774108151495), (5184, 0.013289100474318931), (2480, 0.013286632792247996), (1969, 0.0132857069845294), (745, 0.013274540057191824), (28, 0.013274116035193404), (2486, 0.013273343401742271), (2797, 0.013271353559348524), (3776, 0.013271353559348524), (5922, 0.01326539224708442), (2203, 0.013258232440359466), (1463, 0.013253242086985752), (5197, 0.013252994618722055), (2151, 0.013252448539826205), (6407, 0.013252448539826205), (2614, 0.013247014789869248), (5787, 0.013246991215999716), (2244, 0.013243539155998135), (4604, 0.013238873762948303), (3231, 0.013228243708855834), (2367, 0.013225224644689863), (2414, 0.013225224644689861), (3826, 0.013222959736826323), (5189, 0.013213510160196739), (3779, 0.013208172585025064), (3972, 0.013207820515306383), (2012, 0.01320550591847991), (3092, 0.01320550591847991), (5510, 0.01320550591847991), (4302, 0.013205133583830922), (5473, 0.013204620009480483), (2730, 0.013203407372727094), (1421, 0.01320285987295141), (2638, 0.013196697396845288), (4199, 0.013196485927936876), (3438, 0.013196455898706038), (1770, 0.013194784364367666), (3821

In [20]:
top_sim = sorted_similar_books[:5]
top_sim

[(856, 1.0000000000000002),
 (2453, 0.8703852349478035),
 (3064, 0.8703852349478035),
 (1005, 0.27690004878500996),
 (3420, 0.2627922490745036)]

In [21]:
books = []
for book in top_sim:
    index = book[0]
    book = selected_features[selected_features.index == index]['title'].values[0]
    books.append(book)
books

['Wuthering Heights',
 'Wuthering Heights',
 'Wuthering Heights',
 'Jane Eyre',
 'Emma']

In [38]:
idm = top_sim[0][0]
selected_features[selected_features.index == idm]['title']

RangeIndex(start=0, stop=6810, step=1)

In [49]:
book_genre_ds = data[data['title'] == books[0]]
book_genre_ds_index = book_genre_ds.index
book_index = book_genre_ds_index[0]
book_genre = book_genre_ds['categories'][book_index]
book_author = book_genre_ds['authors'][book_index]
book_author

'Emily Brontë'

In [50]:
book_genre

'Fiction'

In [54]:
close_genre_match = difflib.get_close_matches(book_genre, list_of_all_genres)

In [55]:
close_genre_match

['Fiction', 'Fiction', 'Fiction']

In [56]:
similar_genres = data[data['categories'] == close_genre_match[0]]
similar_authors = data

In [57]:
similar_genres['average_rating']

0       3.85
3       3.93
12      4.03
54      3.71
60      4.14
        ...
6773    3.79
6776    3.92
6778    3.77
6797    3.75
6799    3.22
Name: average_rating, Length: 2588, dtype: float64

In [58]:
def filter_authors(df):
    # Ensure 'book_author' and 'book_genre' are defined before calling this function
    target_authors = df[df['authors'] == book_author]
    target_categories = df[df['categories'] == book_genre]

    # Assign scores based on matches
    df['author_score'] = df['authors'].apply(lambda x: 0.5 if x in target_authors['authors'].values else 0)
    df['genre_score'] = df['categories'].apply(lambda x: 0.5 if x in target_categories['categories'].values else 0)

    return df

In [59]:
def filter_authors(df):
    target_authors = df[df['authors'] == book_author]
    target_categories = df[df['categories'] == book_genre]

    df['author_score'] = df['authors'].apply(lambda x: 0.5 if x in target_authors['authors'].values else 0)
    df['genre_score'] = df['categories'].apply(lambda x: 0.5 if x in target_categories['categories'].values else 0)

    return df

In [60]:
data = filter_authors(data)

In [61]:
data['average_rating'] = data['average_rating'].fillna(0)
data['ratings_count'] = data['num_pages'].fillna(0)
data['num_pages'] = data['ratings_count'].fillna(0)

In [62]:
average_rating_highest = data['average_rating'].max()
ratings_count_highest = data['ratings_count'].max()
data['average_rating_scaled'] = (data['average_rating']/average_rating_highest)*1.5
data['ratings_count_scaled'] = (data['ratings_count']/ratings_count_highest)*1.0
data['ratings'] = data['author_score'] + data['average_rating_scaled'] + data['ratings_count_scaled'] + data['genre_score']

In [63]:
data.isna().sum()

isbn13                      0
isbn10                      0
title                       0
subtitle                 4429
authors                    72
categories                  0
thumbnail                 329
description               262
published_year              6
average_rating              0
num_pages                   0
ratings_count               0
author_score                0
genre_score                 0
average_rating_scaled       0
ratings_count_scaled        0
ratings                     0
dtype: int64

In [64]:
data.nunique()
data['author_score'].unique()

array([0. , 0.5])

In [65]:
sorted_data = data.sort_values(by='ratings', ascending=False)
sorted_data['ratings']

5197    2.529071
2730    2.419000
1937    2.394056
5438    2.351970
3721    2.316693
          ...
459     0.000000
460     0.000000
884     0.000000
4375    0.000000
528     0.000000
Name: ratings, Length: 6810, dtype: float64

In [66]:
recommended_books = sorted_data['title'].head(10)
recommended_books = list(recommended_books)

In [67]:
recommended_books

['The Sword of Truth',
 'The Harry Potter Collection',
 'The Hobbit / The Lord of the Rings',
 'Complete Works',
 'The History of the Lord of the Rings',
 'The Norton Anthology of Short Fiction',
 'The Belgariad Boxed Set',
 'The Complete Novels',
 'The Civil War, a Narrative',
 'Harry Potter']